
<script src="<?php echo base_url();?>assets/plugins/jquery/jquery-2.1.4.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/jquery-blockui/jquery.blockui.js"></script>
<script src="<?php echo base_url();?>assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/switchery/switchery.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/uniform/jquery.uniform.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/classie/classie.js"></script>
<script src="<?php echo base_url();?>assets/plugins/waves/waves.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/3d-bold-navigation/js/main.js"></script>
<script src="<?php echo base_url();?>assets/plugins/jquery-mockjax-master/jquery.mockjax.js"></script>
<script src="<?php echo base_url();?>assets/plugins/moment/moment.js"></script>
<script src="<?php echo base_url();?>assets/plugins/datatables/js/jquery.datatables.min.js"></script>
<script src="<?php echo base_url();?>assets/plugins/x-editable/bootstrap3-editable/js/bootstrap-editable.js"></script>
<script src="<?php echo base_url();?>assets/js/plugins/jQuery-confirm/jquery-confirm.js"></script>
<script src="<?php echo base_url();?>assets/js/mc_js/editor/jquery.jqscribble.js"></script>
<script src="<?php echo base_url();?>assets/js/mc_js/editor/jqscribble.extrabrushes.js"></script>
<script src="<?php echo base_url();?>assets/js/mc_js/editor/jquery.textover.js"></script>
<script src="<?php echo base_url();?>assets/js/modern.js"></script>
<script src="<?php echo base_url(); ?>assets/plugins/select2/js/select2.min.js"></script>
<script src="<?php echo base_url(); ?>assets/js/mc_js/clinics/appointment/medication.js"></script>
